# Generated by Django 4.0.4 on 2022-05-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_movie_description_movie_genre_movie_overview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='uuid',
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbId',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='flyer',
            field=models.URLField(blank=True, default='https://image.tmdb.org/t/p/original/', max_length=100, null=True),
        ),
    ]
