# Generated by Django 4.0.4 on 2022-05-24 17:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_movie_uuid_movie_imdbid_alter_movie_flyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdbId',
        ),
        migrations.AddField(
            model_name='movie',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
