# Generated by Django 4.0.4 on 2022-05-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_movie_date_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='flyer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
