# Generated by Django 4.0.4 on 2022-05-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_movie_popularity_alter_movie_imdbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='uuid',
        ),
    ]
