# Generated by Django 4.0.4 on 2022-05-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_movie_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='imdbid',
            new_name='imdb_id',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='flyer',
            new_name='poster_path',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='date_released',
            new_name='release_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='age_limit',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='videos',
        ),
        migrations.AddField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='revenue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
