# Generated by Django 4.0.4 on 2022-05-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_video_rename_imdbid_movie_imdb_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
