# Generated by Django 4.0.4 on 2022-05-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_myrating_mylist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mylist',
            old_name='user',
            new_name='profile',
        ),
    ]
